In [5]:
import numpy as np
from qutip import *

In [9]:
# generating density matrix rho = (1/3) (rho_1 +  rho_2 +  rho_3)
rho_1 = (1/3)*np.array([[1, 1, 1, 0, 0, 0, 0, 0],
                  [1, 1, 1, 0, 0, 0, 0, 0],
                  [1, 1, 1, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0]])

rho_2 = (1/3)*np.array([[0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 1, -1, -1, 0, 0],
                  [0, 0, 0, -1, 1, 1, 0, 0],
                  [0, 0, 0, -1, 1, 1, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0]]) 

rho_3 = (1/2)*np.array([[0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 1, 0],
                  [0, 0, 0, 0, 0, 0, 0, 1]]) 

rho = (1/3)*(rho_1 + rho_2 + rho_3)
# convert rho into a qutip object
rho = Qobj(rho)
rho

Quantum object: dims=[[8], [8]], shape=(8, 8), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 0.11111111  0.11111111  0.11111111  0.          0.          0.
   0.          0.        ]
 [ 0.11111111  0.11111111  0.11111111  0.          0.          0.
   0.          0.        ]
 [ 0.11111111  0.11111111  0.11111111  0.          0.          0.
   0.          0.        ]
 [ 0.          0.          0.          0.11111111 -0.11111111 -0.11111111
   0.          0.        ]
 [ 0.          0.          0.         -0.11111111  0.11111111  0.11111111
   0.          0.        ]
 [ 0.          0.          0.         -0.11111111  0.11111111  0.11111111
   0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.16666667  0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.16666667]]

In [22]:
paulix = np.array([[0, 1], [1, 0]])
pauliz = np.array([[1, 0], [0, -1]])
g = 1 # Transverse field strength
IsingH = -(np.kron(np.kron(pauliz, pauliz), np.eye(2)) + np.kron(np.eye(2), np.kron(pauliz, pauliz)) + g*(np.kron(np.kron(paulix, np.eye(2)), np.eye(2)) + np.kron(np.kron(np.eye(2), paulix), np.eye(2)) 
        + np.kron(np.kron(np.eye(2), np.eye(2)), paulix))) 
IsingH = Qobj(IsingH)
print("Ising Hamiltonian ", IsingH)

Ising Hamiltonian  Quantum object: dims=[[8], [8]], shape=(8, 8), type='oper', dtype=Dense, isherm=True
Qobj data =
[[-2. -1. -1. -0. -1. -0. -0. -0.]
 [-1. -0. -0. -1. -0. -1. -0. -0.]
 [-1. -0.  2. -1. -0. -0. -1. -0.]
 [-0. -1. -1. -0. -0. -0. -0. -1.]
 [-1. -0. -0. -0. -0. -1. -1. -0.]
 [-0. -1. -0. -0. -1.  2. -0. -1.]
 [-0. -0. -1. -0. -1. -0. -0. -1.]
 [-0. -0. -0. -1. -0. -1. -1. -2.]]


In [23]:
Ising_eigenvalues, Ising_eigenstates = IsingH.eigenstates()
print("Ising eigenvalues ", Ising_eigenvalues)
print("Ising eigenstates ", Ising_eigenstates)

Ising eigenvalues  [-3.49395921 -2.60387547 -1.         -0.10991626  0.10991626  1.
  2.60387547  3.49395921]
Ising eigenstates  [Quantum object: dims=[[8], [1]], shape=(8, 1), type='ket', dtype=Dense
 Qobj data =
 [[-0.53248075]
  [-0.29550452]
  [-0.20449548]
  [-0.29550452]
  [-0.29550452]
  [-0.20449548]
  [-0.29550452]
  [-0.53248075]]
 Quantum object: dims=[[8], [1]], shape=(8, 1), type='ket', dtype=Dense
 Qobj data =
 [[ 0.66399264]
  [ 0.16399264]
  [ 0.07298359]
  [-0.16399264]
  [ 0.16399264]
  [-0.07298359]
  [-0.16399264]
  [-0.66399264]]
 Quantum object: dims=[[8], [1]], shape=(8, 1), type='ket', dtype=Dense
 Qobj data =
 [[-2.66008904e-16]
  [ 5.00000000e-01]
  [-2.49800181e-16]
  [ 5.00000000e-01]
  [-5.00000000e-01]
  [ 3.05311332e-16]
  [-5.00000000e-01]
  [-5.55111512e-17]]
 Quantum object: dims=[[8], [1]], shape=(8, 1), type='ket', dtype=Dense
 Qobj data =
 [[-0.45949716]
  [ 0.36848811]
  [ 0.13151189]
  [ 0.36848811]
  [ 0.36848811]
  [ 0.13151189]
  [ 0.36848811]


In [24]:
Energy = np.trace((IsingH * rho).full())
Energy

(-0.7777777777777778+0j)

In [25]:
eigenvalues = rho.eigenenergies()
print("Eigenvalues of rho ", eigenvalues)

Eigenvalues of rho  [1.35944520e-17 1.35944520e-17 2.80389115e-17 2.80389115e-17
 1.66666667e-01 1.66666667e-01 3.33333333e-01 3.33333333e-01]


In [26]:
rho_min = eigenvalues[7]*Ising_eigenstates[0]*Ising_eigenstates[0].dag() + eigenvalues[6]*Ising_eigenstates[1]*Ising_eigenstates[1].dag() + eigenvalues[5]*Ising_eigenstates[2]*Ising_eigenstates[2].dag() + eigenvalues[4]*Ising_eigenstates[3]*Ising_eigenstates[3].dag() + eigenvalues[3]*Ising_eigenstates[4]*Ising_eigenstates[4].dag() + eigenvalues[2]*Ising_eigenstates[5]*Ising_eigenstates[5].dag() + eigenvalues[1]*Ising_eigenstates[6]*Ising_eigenstates[6].dag() + eigenvalues[0]*Ising_eigenstates[7]*Ising_eigenstates[7].dag()
rho_min

Quantum object: dims=[[8], [8]], shape=(8, 8), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 0.2766636   0.06052692  0.0423786  -0.01206635  0.06052692  0.01007156
  -0.01206635 -0.01726055]
 [ 0.06052692  0.10236942  0.03220946  0.08444036  0.01903608  0.02423028
   0.00110703 -0.01206635]
 [ 0.0423786   0.03220946  0.01859756  0.02423028  0.03220946  0.01504649
   0.02423028  0.01007156]
 [-0.01206635  0.08444036  0.02423028  0.10236942  0.00110703  0.03220946
   0.01903608  0.06052692]
 [ 0.06052692  0.01903608  0.03220946  0.00110703  0.10236942  0.02423028
   0.08444036 -0.01206635]
 [ 0.01007156  0.02423028  0.01504649  0.03220946  0.02423028  0.01859756
   0.03220946  0.0423786 ]
 [-0.01206635  0.00110703  0.02423028  0.01903608  0.08444036  0.03220946
   0.10236942  0.06052692]
 [-0.01726055 -0.01206635  0.01007156  0.06052692 -0.01206635  0.0423786
   0.06052692  0.2766636 ]]

In [27]:
energy_min = np.trace((IsingH * rho_min).full())
energy_min

(-2.2175976037106615+0j)

In [28]:
Ergotropy_rho = Energy - energy_min   # Ergotropy of rho
Ergotropy_rho

(1.4398198259328838+0j)

In [2]:
from qutip.measurement import measure, measurement_statistics

In [29]:
ket00 = basis(4, 0)
ket01 = basis(4, 1)
ket10 = basis(4, 2)
ket11 = basis(4, 3)
Z00, Z01, Z10, Z11 = ket2dm(ket00), ket2dm(ket01), ket2dm(ket10), ket2dm(ket11)
# Projectors for our measurement
P0, P1, P2, P3 = tensor(Z00, identity(2)), tensor(Z01, identity(2)), tensor(Z10, identity(2)), tensor(Z11, identity(2))
P0, P1, P2, P3 = Qobj(P0.full()), Qobj(P1.full()), Qobj(P2.full()), Qobj(P3.full())
Projectors = [P0, P1, P2, P3]

In [34]:
collapsed_states, probabilities = measurement_statistics(rho, Projectors)
collapsed_states[0], probabilities

(Quantum object: dims=[[8], [8]], shape=(8, 8), type='oper', dtype=Dense, isherm=True
 Qobj data =
 [[0.5 0.5 0.  0.  0.  0.  0.  0. ]
  [0.5 0.5 0.  0.  0.  0.  0.  0. ]
  [0.  0.  0.  0.  0.  0.  0.  0. ]
  [0.  0.  0.  0.  0.  0.  0.  0. ]
  [0.  0.  0.  0.  0.  0.  0.  0. ]
  [0.  0.  0.  0.  0.  0.  0.  0. ]
  [0.  0.  0.  0.  0.  0.  0.  0. ]
  [0.  0.  0.  0.  0.  0.  0.  0. ]],
 [0.2222222222222222,
  0.2222222222222222,
  0.2222222222222222,
  0.3333333333333333])

In [35]:
rho_average = np.average(collapsed_states, weights=probabilities)
rho_average

Quantum object: dims=[[8], [8]], shape=(8, 8), type='oper', dtype=Dense, isherm=True
Qobj data =
[[0.11111111 0.11111111 0.         0.         0.         0.
  0.         0.        ]
 [0.11111111 0.11111111 0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.11111111 0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.11111111 0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.11111111 0.11111111
  0.         0.        ]
 [0.         0.         0.         0.         0.11111111 0.11111111
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.16666667 0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.16666667]]

In [48]:
# After applying Haar random unitaries
rho_haar = (1/2)*(probabilities[0]*P0 + probabilities[1]*P1 + probabilities[2]*P2 + probabilities[3]*P3)  
rho_haar

Quantum object: dims=[[8], [8]], shape=(8, 8), type='oper', dtype=Dense, isherm=True
Qobj data =
[[0.11111111 0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.11111111 0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.11111111 0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.11111111 0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.11111111 0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.11111111
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.16666667 0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.16666667]]

In [49]:
np.trace((IsingH * rho_haar).full())

(-0.1111111111111111+0j)

In [44]:
rho_haar.diag()

array([0.11111111, 0.11111111, 0.11111111, 0.11111111, 0.11111111,
       0.11111111, 0.16666667, 0.16666667])

In [46]:
rho_haar_min = rho_haar.diag()[7]*Ising_eigenstates[0]*Ising_eigenstates[0].dag() + rho_haar.diag()[6]*Ising_eigenstates[1]*Ising_eigenstates[1].dag() + rho_haar.diag()[5]*Ising_eigenstates[2]*Ising_eigenstates[2].dag() + rho_haar.diag()[4]*Ising_eigenstates[3]*Ising_eigenstates[3].dag() + rho_haar.diag()[3]*Ising_eigenstates[4]*Ising_eigenstates[4].dag() + rho_haar.diag()[2]*Ising_eigenstates[5]*Ising_eigenstates[5].dag() + rho_haar.diag()[1]*Ising_eigenstates[6]*Ising_eigenstates[6].dag() + rho_haar.diag()[0]*Ising_eigenstates[7]*Ising_eigenstates[7].dag()
rho_haar_min

Quantum object: dims=[[8], [8]], shape=(8, 8), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 0.15135678  0.01479113  0.00874169  0.00269225  0.01479113  0.00335719
   0.00269225 -0.00874169]
 [ 0.01479113  0.11745647  0.00402212  0.00335719  0.00634536  0.00269225
   0.00335719  0.00269225]
 [ 0.00874169  0.00402212  0.11373028  0.00269225  0.00402212  0.00202732
   0.00269225  0.00335719]
 [ 0.00269225  0.00335719  0.00269225  0.11745647  0.00335719  0.00402212
   0.00634536  0.01479113]
 [ 0.01479113  0.00634536  0.00402212  0.00335719  0.11745647  0.00269225
   0.00335719  0.00269225]
 [ 0.00335719  0.00269225  0.00202732  0.00402212  0.00269225  0.11373028
   0.00402212  0.00874169]
 [ 0.00269225  0.00335719  0.00269225  0.00634536  0.00335719  0.00402212
   0.11745647  0.01479113]
 [-0.00874169  0.00269225  0.00335719  0.01479113  0.00269225  0.00874169
   0.01479113  0.15135678]]

In [47]:
energy_haar_min = np.trace((IsingH * rho_haar_min).full())
energy_haar_min

(-0.3387685932802563+0j)

In [52]:
observational_ergotropy = np.trace((IsingH * rho).full()) - energy_haar_min
observational_ergotropy

(-0.43900918449752147+0j)

In [53]:
def algorithm_stage_1(rho, Projectors, Num_shots):
    outcomes = {0.0:0, 1.0:0, 2.0:0, 3.0:0}
    for i in range(num_shots):
        value, _ = measure(rho, Projectors)
        outcomes[round(value)] += 1
    # divide by the number of shots to get the probability
    for key in outcomes.keys():
        outcomes[key] /= num_shots
    return outcomes
num_shots = 1000
probabilities = algorithm_stage1(rho, Projectors, num_shots)
probabilities

{0.0: 0.201, 1.0: 0.236, 2.0: 0.235, 3.0: 0.328}

In [72]:
rho_avg_stage1 = (1/2)*(probabilities[0]*P0 + probabilities[1]*P1 + probabilities[2]*P2 + probabilities[3]*P3)
#stage1_eig, stage1_vec = np.linalg.eig(rho_avg_stage1.full())
stage1_eig, stage1_vec = rho_avg_stage1.eigenstates()
#rho_avg_stage1
print(stage1_eig, stage1_vec)
sortindex = np.argsort(stage1_eig)
sortindex

[0.1005 0.1005 0.1175 0.1175 0.118  0.118  0.164  0.164 ] [Quantum object: dims=[[8], [1]], shape=(8, 1), type='ket', dtype=Dense
 Qobj data =
 [[1.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]]
 Quantum object: dims=[[8], [1]], shape=(8, 1), type='ket', dtype=Dense
 Qobj data =
 [[0.]
  [1.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]]
 Quantum object: dims=[[8], [1]], shape=(8, 1), type='ket', dtype=Dense
 Qobj data =
 [[0.]
  [0.]
  [0.]
  [0.]
  [1.]
  [0.]
  [0.]
  [0.]]
 Quantum object: dims=[[8], [1]], shape=(8, 1), type='ket', dtype=Dense
 Qobj data =
 [[0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [1.]
  [0.]
  [0.]]
 Quantum object: dims=[[8], [1]], shape=(8, 1), type='ket', dtype=Dense
 Qobj data =
 [[0.]
  [0.]
  [1.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]]
 Quantum object: dims=[[8], [1]], shape=(8, 1), type='ket', dtype=Dense
 Qobj data =
 [[0.]
  [0.]
  [0.]
  [1.]
  [0.]
  [0.]
  [0.]
  [0.]]
 Quantum object: dims=[[8], [1]], shape=(8, 1), type='ket', dtype=Dense
 Qobj data =
 [[0.

array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64)

In [74]:
Ising_eigenstates[0]*stage1_vec[7].dag()

Quantum object: dims=[[8], [8]], shape=(8, 8), type='oper', dtype=Dense, isherm=False
Qobj data =
[[ 0.          0.          0.          0.          0.          0.
   0.         -0.53248075]
 [ 0.          0.          0.          0.          0.          0.
   0.         -0.29550452]
 [ 0.          0.          0.          0.          0.          0.
   0.         -0.20449548]
 [ 0.          0.          0.          0.          0.          0.
   0.         -0.29550452]
 [ 0.          0.          0.          0.          0.          0.
   0.         -0.29550452]
 [ 0.          0.          0.          0.          0.          0.
   0.         -0.20449548]
 [ 0.          0.          0.          0.          0.          0.
   0.         -0.29550452]
 [ 0.          0.          0.          0.          0.          0.
   0.         -0.53248075]]

In [75]:
# Construct U_global 
U_global = Ising_eigenstates[0]*stage1_vec[sortindex[-1]].dag() + Ising_eigenstates[1]*stage1_vec[sortindex[-2]].dag() + Ising_eigenstates[2]*stage1_vec[sortindex[-3]].dag() + Ising_eigenstates[3]*stage1_vec[sortindex[-4]].dag() + Ising_eigenstates[4]*stage1_vec[sortindex[-5]].dag() + Ising_eigenstates[5]*stage1_vec[sortindex[-6]].dag() + Ising_eigenstates[6]*stage1_vec[sortindex[-7]].dag() + Ising_eigenstates[7]*stage1_vec[sortindex[-8]].dag()
U_global


Quantum object: dims=[[8], [8]], shape=(8, 8), type='oper', dtype=Dense, isherm=False
Qobj data =
[[ 2.04495476e-01 -7.29835903e-02 -4.59497163e-01 -2.66008904e-16
  -7.49402797e-17  1.31511885e-01  6.63992639e-01 -5.32480753e-01]
 [-2.95504524e-01 -1.63992639e-01  3.68488115e-01  5.00000000e-01
   5.00000000e-01 -3.68488115e-01  1.63992639e-01 -2.95504524e-01]
 [-5.32480753e-01  6.63992639e-01  1.31511885e-01 -2.49800181e-16
   2.49800181e-16  4.59497163e-01  7.29835903e-02 -2.04495476e-01]
 [ 2.95504524e-01 -1.63992639e-01  3.68488115e-01  5.00000000e-01
  -5.00000000e-01  3.68488115e-01 -1.63992639e-01 -2.95504524e-01]
 [-2.95504524e-01 -1.63992639e-01  3.68488115e-01 -5.00000000e-01
  -5.00000000e-01 -3.68488115e-01  1.63992639e-01 -2.95504524e-01]
 [ 5.32480753e-01  6.63992639e-01  1.31511885e-01  3.05311332e-16
  -6.93889390e-17 -4.59497163e-01 -7.29835903e-02 -2.04495476e-01]
 [ 2.95504524e-01 -1.63992639e-01  3.68488115e-01 -5.00000000e-01
   5.00000000e-01  3.68488115e-01 -1.6

In [20]:
I, X, Y, Z = qeye(2), sigmax(), sigmay(), sigmaz()
pauli_group = []
for op in [I, X, Y, Z]:
    pauli_group.append(op)
    pauli_group.append(-1*op)
    pauli_group.append(1j*op)
    pauli_group.append(-1j*op)

In [78]:
# stage 2 of algorithm
def algorithm_stage_2(density_matrix, hamiltonian, U_global, Projectors, iter):
    energy_outcomes = []
    for iteration in range(iter):
        if np.random.choice([0, 1]) == 0:
            outcome, _ = measure(density_matrix, hamiltonian)
            energy_outcomes.append(outcome)
        else:
            _, post_measure_state = measure(density_matrix, Projectors)
            u_random = np.random.choice(pauli_group)

            u = tensor(qeye(4), u_random)  # currently hard coded. We will change 4 to general dimension
            u = Qobj(u.full()) # converting to np.array and again back to Qobj to match the dimension
            density_matrix = u * post_measure_state * u.dag()
           
            #U_global = qeye(8)      # global unitary
            density_matrix = U_global * density_matrix * U_global.dag()

            # measure -H
            outcome, _ = measure(density_matrix, -1*hamiltonian)
            energy_outcomes.append(outcome)
    Ergotropy = 2*np.mean(energy_outcomes)        
    return Ergotropy

In [79]:
algorithm_stage_2(rho, IsingH, U_global, Projectors, 1000)

-0.15814810316536324