In [1]:
import numpy as np
from qutip import *

In [2]:
# generating density matrix rho = (1/3) (rho_1 +  rho_2 +  rho_3)
rho_1 = (1/3)*np.array([[1, 1, 1, 0, 0, 0, 0, 0],
                  [1, 1, 1, 0, 0, 0, 0, 0],
                  [1, 1, 1, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0]])

rho_2 = (1/3)*np.array([[0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 1, -1, -1, 0, 0],
                  [0, 0, 0, -1, 1, 1, 0, 0],
                  [0, 0, 0, -1, 1, 1, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0]]) 

rho_3 = (1/2)*np.array([[0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 1, 0],
                  [0, 0, 0, 0, 0, 0, 0, 1]]) 

rho = (1/3)*(rho_1 + rho_2 + rho_3)

# convert rho into a qutip object
rho = Qobj(rho)

rho

Quantum object: dims=[[8], [8]], shape=(8, 8), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 0.11111111  0.11111111  0.11111111  0.          0.          0.
   0.          0.        ]
 [ 0.11111111  0.11111111  0.11111111  0.          0.          0.
   0.          0.        ]
 [ 0.11111111  0.11111111  0.11111111  0.          0.          0.
   0.          0.        ]
 [ 0.          0.          0.          0.11111111 -0.11111111 -0.11111111
   0.          0.        ]
 [ 0.          0.          0.         -0.11111111  0.11111111  0.11111111
   0.          0.        ]
 [ 0.          0.          0.         -0.11111111  0.11111111  0.11111111
   0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.16666667  0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.16666667]]

In [8]:
paulix = np.array([[0, 1], [1, 0]])
pauliz = np.array([[1, 0], [0, -1]])
g = 1 # Transverse field strength
IsingH = -(np.kron(np.kron(pauliz, pauliz), np.eye(2)) + np.kron(np.eye(2), np.kron(pauliz, pauliz)) + g*(np.kron(np.kron(paulix, np.eye(2)), np.eye(2)) + np.kron(np.kron(np.eye(2), paulix), np.eye(2)) 
        + np.kron(np.kron(np.eye(2), np.eye(2)), paulix))) 
IsingH = Qobj(IsingH)
print("Ising Hamiltonian ", IsingH)

Ising Hamiltonian  Quantum object: dims=[[8], [8]], shape=(8, 8), type='oper', dtype=Dense, isherm=True
Qobj data =
[[-2. -1. -1. -0. -1. -0. -0. -0.]
 [-1. -0. -0. -1. -0. -1. -0. -0.]
 [-1. -0.  2. -1. -0. -0. -1. -0.]
 [-0. -1. -1. -0. -0. -0. -0. -1.]
 [-1. -0. -0. -0. -0. -1. -1. -0.]
 [-0. -1. -0. -0. -1.  2. -0. -1.]
 [-0. -0. -1. -0. -1. -0. -0. -1.]
 [-0. -0. -0. -1. -0. -1. -1. -2.]]
Eigenvalues  [-3.49395921 -2.60387547 -1.         -0.10991626  0.10991626  1.
  2.60387547  3.49395921]


In [13]:
Ising_eigenvalues, Ising_eigenstates = IsingH.eigenstates()
print("Ising eigenvalues ", Ising_eigenvalues)
print("Ising eigenstates ", Ising_eigenstates)

Ising eigenvalues  [-3.49395921 -2.60387547 -1.         -0.10991626  0.10991626  1.
  2.60387547  3.49395921]
Ising eigenstates  [Quantum object: dims=[[8], [1]], shape=(8, 1), type='ket', dtype=Dense
 Qobj data =
 [[-0.53248075]
  [-0.29550452]
  [-0.20449548]
  [-0.29550452]
  [-0.29550452]
  [-0.20449548]
  [-0.29550452]
  [-0.53248075]]
 Quantum object: dims=[[8], [1]], shape=(8, 1), type='ket', dtype=Dense
 Qobj data =
 [[ 0.66399264]
  [ 0.16399264]
  [ 0.07298359]
  [-0.16399264]
  [ 0.16399264]
  [-0.07298359]
  [-0.16399264]
  [-0.66399264]]
 Quantum object: dims=[[8], [1]], shape=(8, 1), type='ket', dtype=Dense
 Qobj data =
 [[-2.66008904e-16]
  [ 5.00000000e-01]
  [-2.49800181e-16]
  [ 5.00000000e-01]
  [-5.00000000e-01]
  [ 3.05311332e-16]
  [-5.00000000e-01]
  [-5.55111512e-17]]
 Quantum object: dims=[[8], [1]], shape=(8, 1), type='ket', dtype=Dense
 Qobj data =
 [[-0.45949716]
  [ 0.36848811]
  [ 0.13151189]
  [ 0.36848811]
  [ 0.36848811]
  [ 0.13151189]
  [ 0.36848811]


In [4]:
Energy = np.trace((IsingH * rho).full())
Energy

(0.7777777777777778+0j)

In [16]:
eigenvalues = rho.eigenenergies()
print("Eigenvalues of rho ", eigenvalues)

Eigenvalues of rho  [1.35944520e-17 1.35944520e-17 2.80389115e-17 2.80389115e-17
 1.66666667e-01 1.66666667e-01 3.33333333e-01 3.33333333e-01]


In [17]:
rho_min = eigenvalues[7]*Ising_eigenstates[0]*Ising_eigenstates[0].dag() + eigenvalues[6]*Ising_eigenstates[1]*Ising_eigenstates[1].dag() + eigenvalues[5]*Ising_eigenstates[2]*Ising_eigenstates[2].dag() + eigenvalues[4]*Ising_eigenstates[3]*Ising_eigenstates[3].dag() + eigenvalues[3]*Ising_eigenstates[4]*Ising_eigenstates[4].dag() + eigenvalues[2]*Ising_eigenstates[5]*Ising_eigenstates[5].dag() + eigenvalues[1]*Ising_eigenstates[6]*Ising_eigenstates[6].dag() + eigenvalues[0]*Ising_eigenstates[7]*Ising_eigenstates[7].dag()
rho_min

Quantum object: dims=[[8], [8]], shape=(8, 8), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 0.2766636   0.06052692  0.0423786  -0.01206635  0.06052692  0.01007156
  -0.01206635 -0.01726055]
 [ 0.06052692  0.10236942  0.03220946  0.08444036  0.01903608  0.02423028
   0.00110703 -0.01206635]
 [ 0.0423786   0.03220946  0.01859756  0.02423028  0.03220946  0.01504649
   0.02423028  0.01007156]
 [-0.01206635  0.08444036  0.02423028  0.10236942  0.00110703  0.03220946
   0.01903608  0.06052692]
 [ 0.06052692  0.01903608  0.03220946  0.00110703  0.10236942  0.02423028
   0.08444036 -0.01206635]
 [ 0.01007156  0.02423028  0.01504649  0.03220946  0.02423028  0.01859756
   0.03220946  0.0423786 ]
 [-0.01206635  0.00110703  0.02423028  0.01903608  0.08444036  0.03220946
   0.10236942  0.06052692]
 [-0.01726055 -0.01206635  0.01007156  0.06052692 -0.01206635  0.0423786
   0.06052692  0.2766636 ]]

In [18]:
energy_min = np.trace((IsingH * rho_min).full())
energy_min

(-2.2175976037106615+0j)

In [19]:
from qutip.measurement import measure, measurement_statistics